### ISSUE TITLE
Camel case field names not preserved in getters

### ISSUE THREAD

**Issue by ian-h-chamberlain** [masaushi/accessory#29]
For example, a field:
```go
type Config struct {
	nodeName string `accessor:"getter"`
}
```

generates output like
```go
func (c *Config) Nodename() string {
	if c == nil {
		return ""
	}
	return c.nodeName
}
```
whereas I would expect the method to be called `NodeName()`.

I believe this can easily be resolved using `cases.NoLower` in the [method names generator](https://github.com/masaushi/accessory/blob/main/internal/accessor/generator.go#L205-L218), but I suppose it would be a breaking change, so maybe needs a CLI option (or version bump)?
https://goplay.tools/snippet/5NfnKP4tfSn

**Comment by masaushi** [comment]
@ian-h-chamberlain 
Thank you for reporting the issue! Your included solution is greatly appreciated.

As you pointed out, using `cases.NoLower` to resolve the issue would result in a breaking change. However, I think that the majority of users expect the generated code to be `NodeName()` rather than `Nodename()`.
Therefore, upgrading the version would be a better choise, and it is not necessary to make it a command line option."
